version: 2

archives:
  - id: archive
    name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
before:
  hooks:
    - make tfgen
builds:
  - binary: pulumi-resource-huaweicloud
    dir: provider
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - windows
      - linux
    ldflags:
      # The line below MUST align with the module in current provider/go.mod
      - -X github.com/masikrus/pulumi-huaweicloud/provider/pkg/version.Version={{.Tag }}
    main: ./cmd/pulumi-resource-huaweicloud/
changelog:
  filters:
    exclude:
      - '^docs:'
      - '^chore:'
release:
  # Visit your project's GitHub Releases page to publish this release.
  draft: true
snapshot:
  version_template: '{{ .Tag }}-SNAPSHOT'
