# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs

__all__ = [
    'GetPredefinedTemplatesResult',
    'AwaitableGetPredefinedTemplatesResult',
    'get_predefined_templates',
    'get_predefined_templates_output',
]

@pulumi.output_type
class GetPredefinedTemplatesResult:
    """
    A collection of values returned by getPredefinedTemplates.
    """
    def __init__(__self__, id=None, region=None, templates=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if region and not isinstance(region, str):
            raise TypeError("Expected argument 'region' to be a str")
        pulumi.set(__self__, "region", region)
        if templates and not isinstance(templates, list):
            raise TypeError("Expected argument 'templates' to be a list")
        pulumi.set(__self__, "templates", templates)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def region(self) -> _builtins.str:
        return pulumi.get(self, "region")

    @_builtins.property
    @pulumi.getter
    def templates(self) -> Sequence['outputs.GetPredefinedTemplatesTemplateResult']:
        """
        Information about the pre-defined templates list.
        """
        return pulumi.get(self, "templates")


class AwaitableGetPredefinedTemplatesResult(GetPredefinedTemplatesResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetPredefinedTemplatesResult(
            id=self.id,
            region=self.region,
            templates=self.templates)


def get_predefined_templates(region: Optional[_builtins.str] = None,
                             opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetPredefinedTemplatesResult:
    """
    Use this data source to list pre-defined templates in Resource Governance Center.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_huaweicloud as huaweicloud

    test = huaweicloud.Rgc.get_predefined_templates()
    ```


    :param _builtins.str region: Specifies the region in which to create the resource.
           If omitted, the provider-level region will be used. Changing this parameter will create a new resource.
    """
    __args__ = dict()
    __args__['region'] = region
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('huaweicloud:Rgc/getPredefinedTemplates:getPredefinedTemplates', __args__, opts=opts, typ=GetPredefinedTemplatesResult).value

    return AwaitableGetPredefinedTemplatesResult(
        id=pulumi.get(__ret__, 'id'),
        region=pulumi.get(__ret__, 'region'),
        templates=pulumi.get(__ret__, 'templates'))
def get_predefined_templates_output(region: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                    opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetPredefinedTemplatesResult]:
    """
    Use this data source to list pre-defined templates in Resource Governance Center.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_huaweicloud as huaweicloud

    test = huaweicloud.Rgc.get_predefined_templates()
    ```


    :param _builtins.str region: Specifies the region in which to create the resource.
           If omitted, the provider-level region will be used. Changing this parameter will create a new resource.
    """
    __args__ = dict()
    __args__['region'] = region
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('huaweicloud:Rgc/getPredefinedTemplates:getPredefinedTemplates', __args__, opts=opts, typ=GetPredefinedTemplatesResult)
    return __ret__.apply(lambda __response__: GetPredefinedTemplatesResult(
        id=pulumi.get(__response__, 'id'),
        region=pulumi.get(__response__, 'region'),
        templates=pulumi.get(__response__, 'templates')))
