# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = ['ResourceAggregationPendingRequestDeleteArgs', 'ResourceAggregationPendingRequestDelete']

@pulumi.input_type
class ResourceAggregationPendingRequestDeleteArgs:
    def __init__(__self__, *,
                 requester_account_id: pulumi.Input[_builtins.str],
                 enable_force_new: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a ResourceAggregationPendingRequestDelete resource.

        :param pulumi.Input[_builtins.str] requester_account_id: Specifies the ID of the account that requests data aggregation.
        """
        pulumi.set(__self__, "requester_account_id", requester_account_id)
        if enable_force_new is not None:
            pulumi.set(__self__, "enable_force_new", enable_force_new)

    @_builtins.property
    @pulumi.getter(name="requesterAccountId")
    def requester_account_id(self) -> pulumi.Input[_builtins.str]:
        """
        Specifies the ID of the account that requests data aggregation.
        """
        return pulumi.get(self, "requester_account_id")

    @requester_account_id.setter
    def requester_account_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "requester_account_id", value)

    @_builtins.property
    @pulumi.getter(name="enableForceNew")
    def enable_force_new(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "enable_force_new")

    @enable_force_new.setter
    def enable_force_new(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "enable_force_new", value)


@pulumi.input_type
class _ResourceAggregationPendingRequestDeleteState:
    def __init__(__self__, *,
                 enable_force_new: Optional[pulumi.Input[_builtins.str]] = None,
                 requester_account_id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering ResourceAggregationPendingRequestDelete resources.

        :param pulumi.Input[_builtins.str] requester_account_id: Specifies the ID of the account that requests data aggregation.
        """
        if enable_force_new is not None:
            pulumi.set(__self__, "enable_force_new", enable_force_new)
        if requester_account_id is not None:
            pulumi.set(__self__, "requester_account_id", requester_account_id)

    @_builtins.property
    @pulumi.getter(name="enableForceNew")
    def enable_force_new(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "enable_force_new")

    @enable_force_new.setter
    def enable_force_new(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "enable_force_new", value)

    @_builtins.property
    @pulumi.getter(name="requesterAccountId")
    def requester_account_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Specifies the ID of the account that requests data aggregation.
        """
        return pulumi.get(self, "requester_account_id")

    @requester_account_id.setter
    def requester_account_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "requester_account_id", value)


@pulumi.type_token("huaweicloud:Rms/resourceAggregationPendingRequestDelete:ResourceAggregationPendingRequestDelete")
class ResourceAggregationPendingRequestDelete(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 enable_force_new: Optional[pulumi.Input[_builtins.str]] = None,
                 requester_account_id: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Manages an RMS pending authorization request delete resource within HuaweiCloud resources.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_huaweicloud as huaweicloud

        config = pulumi.Config()
        requester_account_id = config.require_object("requesterAccountId")
        test = huaweicloud.rms.ResourceAggregationPendingRequestDelete("test", requester_account_id=requester_account_id)
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] requester_account_id: Specifies the ID of the account that requests data aggregation.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ResourceAggregationPendingRequestDeleteArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Manages an RMS pending authorization request delete resource within HuaweiCloud resources.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_huaweicloud as huaweicloud

        config = pulumi.Config()
        requester_account_id = config.require_object("requesterAccountId")
        test = huaweicloud.rms.ResourceAggregationPendingRequestDelete("test", requester_account_id=requester_account_id)
        ```


        :param str resource_name: The name of the resource.
        :param ResourceAggregationPendingRequestDeleteArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ResourceAggregationPendingRequestDeleteArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 enable_force_new: Optional[pulumi.Input[_builtins.str]] = None,
                 requester_account_id: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ResourceAggregationPendingRequestDeleteArgs.__new__(ResourceAggregationPendingRequestDeleteArgs)

            __props__.__dict__["enable_force_new"] = enable_force_new
            if requester_account_id is None and not opts.urn:
                raise TypeError("Missing required property 'requester_account_id'")
            __props__.__dict__["requester_account_id"] = requester_account_id
        super(ResourceAggregationPendingRequestDelete, __self__).__init__(
            'huaweicloud:Rms/resourceAggregationPendingRequestDelete:ResourceAggregationPendingRequestDelete',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            enable_force_new: Optional[pulumi.Input[_builtins.str]] = None,
            requester_account_id: Optional[pulumi.Input[_builtins.str]] = None) -> 'ResourceAggregationPendingRequestDelete':
        """
        Get an existing ResourceAggregationPendingRequestDelete resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] requester_account_id: Specifies the ID of the account that requests data aggregation.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ResourceAggregationPendingRequestDeleteState.__new__(_ResourceAggregationPendingRequestDeleteState)

        __props__.__dict__["enable_force_new"] = enable_force_new
        __props__.__dict__["requester_account_id"] = requester_account_id
        return ResourceAggregationPendingRequestDelete(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="enableForceNew")
    def enable_force_new(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "enable_force_new")

    @_builtins.property
    @pulumi.getter(name="requesterAccountId")
    def requester_account_id(self) -> pulumi.Output[_builtins.str]:
        """
        Specifies the ID of the account that requests data aggregation.
        """
        return pulumi.get(self, "requester_account_id")

