# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs

__all__ = [
    'GetImageSignaturePolicyExecutionRecordTasksResult',
    'AwaitableGetImageSignaturePolicyExecutionRecordTasksResult',
    'get_image_signature_policy_execution_record_tasks',
    'get_image_signature_policy_execution_record_tasks_output',
]

@pulumi.output_type
class GetImageSignaturePolicyExecutionRecordTasksResult:
    """
    A collection of values returned by getImageSignaturePolicyExecutionRecordTasks.
    """
    def __init__(__self__, execution_id=None, id=None, instance_id=None, namespace_name=None, policy_id=None, region=None, tasks=None):
        if execution_id and not isinstance(execution_id, str):
            raise TypeError("Expected argument 'execution_id' to be a str")
        pulumi.set(__self__, "execution_id", execution_id)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if instance_id and not isinstance(instance_id, str):
            raise TypeError("Expected argument 'instance_id' to be a str")
        pulumi.set(__self__, "instance_id", instance_id)
        if namespace_name and not isinstance(namespace_name, str):
            raise TypeError("Expected argument 'namespace_name' to be a str")
        pulumi.set(__self__, "namespace_name", namespace_name)
        if policy_id and not isinstance(policy_id, str):
            raise TypeError("Expected argument 'policy_id' to be a str")
        pulumi.set(__self__, "policy_id", policy_id)
        if region and not isinstance(region, str):
            raise TypeError("Expected argument 'region' to be a str")
        pulumi.set(__self__, "region", region)
        if tasks and not isinstance(tasks, list):
            raise TypeError("Expected argument 'tasks' to be a list")
        pulumi.set(__self__, "tasks", tasks)

    @_builtins.property
    @pulumi.getter(name="executionId")
    def execution_id(self) -> _builtins.str:
        """
        Indicates the execution record ID.
        """
        return pulumi.get(self, "execution_id")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="instanceId")
    def instance_id(self) -> _builtins.str:
        return pulumi.get(self, "instance_id")

    @_builtins.property
    @pulumi.getter(name="namespaceName")
    def namespace_name(self) -> _builtins.str:
        return pulumi.get(self, "namespace_name")

    @_builtins.property
    @pulumi.getter(name="policyId")
    def policy_id(self) -> _builtins.str:
        return pulumi.get(self, "policy_id")

    @_builtins.property
    @pulumi.getter
    def region(self) -> _builtins.str:
        return pulumi.get(self, "region")

    @_builtins.property
    @pulumi.getter
    def tasks(self) -> Sequence['outputs.GetImageSignaturePolicyExecutionRecordTasksTaskResult']:
        """
        Indicates the execution records.
        """
        return pulumi.get(self, "tasks")


class AwaitableGetImageSignaturePolicyExecutionRecordTasksResult(GetImageSignaturePolicyExecutionRecordTasksResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetImageSignaturePolicyExecutionRecordTasksResult(
            execution_id=self.execution_id,
            id=self.id,
            instance_id=self.instance_id,
            namespace_name=self.namespace_name,
            policy_id=self.policy_id,
            region=self.region,
            tasks=self.tasks)


def get_image_signature_policy_execution_record_tasks(execution_id: Optional[_builtins.str] = None,
                                                      instance_id: Optional[_builtins.str] = None,
                                                      namespace_name: Optional[_builtins.str] = None,
                                                      policy_id: Optional[_builtins.str] = None,
                                                      region: Optional[_builtins.str] = None,
                                                      opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetImageSignaturePolicyExecutionRecordTasksResult:
    """
    Use this data source to get the list of SWR enterprise image signature policy execution record tasks.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_huaweicloud as huaweicloud

    config = pulumi.Config()
    instance_id = config.require_object("instanceId")
    namespace_name = config.require_object("namespaceName")
    policy_id = config.require_object("policyId")
    execution_id = config.require_object("executionId")
    test = huaweicloud.SwrEnterprise.get_image_signature_policy_execution_record_tasks(instance_id=instance_id,
        namespace_name=namespace_name,
        policy_id=policy_id,
        execution_id=execution_id)
    ```


    :param _builtins.str execution_id: Specifies the execution record ID.
    :param _builtins.str instance_id: Specifies the enterprise instance ID.
    :param _builtins.str namespace_name: Specifies the namespace name.
    :param _builtins.str policy_id: Specifies the policy ID.
    :param _builtins.str region: Specifies the region in which to query the resource.
           If omitted, the provider-level region will be used.
    """
    __args__ = dict()
    __args__['executionId'] = execution_id
    __args__['instanceId'] = instance_id
    __args__['namespaceName'] = namespace_name
    __args__['policyId'] = policy_id
    __args__['region'] = region
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('huaweicloud:SwrEnterprise/getImageSignaturePolicyExecutionRecordTasks:getImageSignaturePolicyExecutionRecordTasks', __args__, opts=opts, typ=GetImageSignaturePolicyExecutionRecordTasksResult).value

    return AwaitableGetImageSignaturePolicyExecutionRecordTasksResult(
        execution_id=pulumi.get(__ret__, 'execution_id'),
        id=pulumi.get(__ret__, 'id'),
        instance_id=pulumi.get(__ret__, 'instance_id'),
        namespace_name=pulumi.get(__ret__, 'namespace_name'),
        policy_id=pulumi.get(__ret__, 'policy_id'),
        region=pulumi.get(__ret__, 'region'),
        tasks=pulumi.get(__ret__, 'tasks'))
def get_image_signature_policy_execution_record_tasks_output(execution_id: Optional[pulumi.Input[_builtins.str]] = None,
                                                             instance_id: Optional[pulumi.Input[_builtins.str]] = None,
                                                             namespace_name: Optional[pulumi.Input[_builtins.str]] = None,
                                                             policy_id: Optional[pulumi.Input[_builtins.str]] = None,
                                                             region: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                                             opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetImageSignaturePolicyExecutionRecordTasksResult]:
    """
    Use this data source to get the list of SWR enterprise image signature policy execution record tasks.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_huaweicloud as huaweicloud

    config = pulumi.Config()
    instance_id = config.require_object("instanceId")
    namespace_name = config.require_object("namespaceName")
    policy_id = config.require_object("policyId")
    execution_id = config.require_object("executionId")
    test = huaweicloud.SwrEnterprise.get_image_signature_policy_execution_record_tasks(instance_id=instance_id,
        namespace_name=namespace_name,
        policy_id=policy_id,
        execution_id=execution_id)
    ```


    :param _builtins.str execution_id: Specifies the execution record ID.
    :param _builtins.str instance_id: Specifies the enterprise instance ID.
    :param _builtins.str namespace_name: Specifies the namespace name.
    :param _builtins.str policy_id: Specifies the policy ID.
    :param _builtins.str region: Specifies the region in which to query the resource.
           If omitted, the provider-level region will be used.
    """
    __args__ = dict()
    __args__['executionId'] = execution_id
    __args__['instanceId'] = instance_id
    __args__['namespaceName'] = namespace_name
    __args__['policyId'] = policy_id
    __args__['region'] = region
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('huaweicloud:SwrEnterprise/getImageSignaturePolicyExecutionRecordTasks:getImageSignaturePolicyExecutionRecordTasks', __args__, opts=opts, typ=GetImageSignaturePolicyExecutionRecordTasksResult)
    return __ret__.apply(lambda __response__: GetImageSignaturePolicyExecutionRecordTasksResult(
        execution_id=pulumi.get(__response__, 'execution_id'),
        id=pulumi.get(__response__, 'id'),
        instance_id=pulumi.get(__response__, 'instance_id'),
        namespace_name=pulumi.get(__response__, 'namespace_name'),
        policy_id=pulumi.get(__response__, 'policy_id'),
        region=pulumi.get(__response__, 'region'),
        tasks=pulumi.get(__response__, 'tasks')))
