# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs

__all__ = [
    'GetPrivateTransitSubnetsResult',
    'AwaitableGetPrivateTransitSubnetsResult',
    'get_private_transit_subnets',
    'get_private_transit_subnets_output',
]

@pulumi.output_type
class GetPrivateTransitSubnetsResult:
    """
    A collection of values returned by getPrivateTransitSubnets.
    """
    def __init__(__self__, descriptions=None, id=None, ids=None, names=None, region=None, statuses=None, transit_subnets=None, virsubnet_ids=None, virsubnet_project_ids=None, vpc_ids=None):
        if descriptions and not isinstance(descriptions, list):
            raise TypeError("Expected argument 'descriptions' to be a list")
        pulumi.set(__self__, "descriptions", descriptions)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if ids and not isinstance(ids, list):
            raise TypeError("Expected argument 'ids' to be a list")
        pulumi.set(__self__, "ids", ids)
        if names and not isinstance(names, list):
            raise TypeError("Expected argument 'names' to be a list")
        pulumi.set(__self__, "names", names)
        if region and not isinstance(region, str):
            raise TypeError("Expected argument 'region' to be a str")
        pulumi.set(__self__, "region", region)
        if statuses and not isinstance(statuses, list):
            raise TypeError("Expected argument 'statuses' to be a list")
        pulumi.set(__self__, "statuses", statuses)
        if transit_subnets and not isinstance(transit_subnets, list):
            raise TypeError("Expected argument 'transit_subnets' to be a list")
        pulumi.set(__self__, "transit_subnets", transit_subnets)
        if virsubnet_ids and not isinstance(virsubnet_ids, list):
            raise TypeError("Expected argument 'virsubnet_ids' to be a list")
        pulumi.set(__self__, "virsubnet_ids", virsubnet_ids)
        if virsubnet_project_ids and not isinstance(virsubnet_project_ids, list):
            raise TypeError("Expected argument 'virsubnet_project_ids' to be a list")
        pulumi.set(__self__, "virsubnet_project_ids", virsubnet_project_ids)
        if vpc_ids and not isinstance(vpc_ids, list):
            raise TypeError("Expected argument 'vpc_ids' to be a list")
        pulumi.set(__self__, "vpc_ids", vpc_ids)

    @_builtins.property
    @pulumi.getter
    def descriptions(self) -> Optional[Sequence[_builtins.str]]:
        return pulumi.get(self, "descriptions")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def ids(self) -> Optional[Sequence[_builtins.str]]:
        return pulumi.get(self, "ids")

    @_builtins.property
    @pulumi.getter
    def names(self) -> Optional[Sequence[_builtins.str]]:
        return pulumi.get(self, "names")

    @_builtins.property
    @pulumi.getter
    def region(self) -> _builtins.str:
        return pulumi.get(self, "region")

    @_builtins.property
    @pulumi.getter
    def statuses(self) -> Optional[Sequence[_builtins.str]]:
        return pulumi.get(self, "statuses")

    @_builtins.property
    @pulumi.getter(name="transitSubnets")
    def transit_subnets(self) -> Sequence['outputs.GetPrivateTransitSubnetsTransitSubnetResult']:
        return pulumi.get(self, "transit_subnets")

    @_builtins.property
    @pulumi.getter(name="virsubnetIds")
    def virsubnet_ids(self) -> Optional[Sequence[_builtins.str]]:
        return pulumi.get(self, "virsubnet_ids")

    @_builtins.property
    @pulumi.getter(name="virsubnetProjectIds")
    def virsubnet_project_ids(self) -> Optional[Sequence[_builtins.str]]:
        return pulumi.get(self, "virsubnet_project_ids")

    @_builtins.property
    @pulumi.getter(name="vpcIds")
    def vpc_ids(self) -> Optional[Sequence[_builtins.str]]:
        return pulumi.get(self, "vpc_ids")


class AwaitableGetPrivateTransitSubnetsResult(GetPrivateTransitSubnetsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetPrivateTransitSubnetsResult(
            descriptions=self.descriptions,
            id=self.id,
            ids=self.ids,
            names=self.names,
            region=self.region,
            statuses=self.statuses,
            transit_subnets=self.transit_subnets,
            virsubnet_ids=self.virsubnet_ids,
            virsubnet_project_ids=self.virsubnet_project_ids,
            vpc_ids=self.vpc_ids)


def get_private_transit_subnets(descriptions: Optional[Sequence[_builtins.str]] = None,
                                ids: Optional[Sequence[_builtins.str]] = None,
                                names: Optional[Sequence[_builtins.str]] = None,
                                region: Optional[_builtins.str] = None,
                                statuses: Optional[Sequence[_builtins.str]] = None,
                                virsubnet_ids: Optional[Sequence[_builtins.str]] = None,
                                virsubnet_project_ids: Optional[Sequence[_builtins.str]] = None,
                                vpc_ids: Optional[Sequence[_builtins.str]] = None,
                                opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetPrivateTransitSubnetsResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['descriptions'] = descriptions
    __args__['ids'] = ids
    __args__['names'] = names
    __args__['region'] = region
    __args__['statuses'] = statuses
    __args__['virsubnetIds'] = virsubnet_ids
    __args__['virsubnetProjectIds'] = virsubnet_project_ids
    __args__['vpcIds'] = vpc_ids
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('huaweicloud:Nat/getPrivateTransitSubnets:getPrivateTransitSubnets', __args__, opts=opts, typ=GetPrivateTransitSubnetsResult).value

    return AwaitableGetPrivateTransitSubnetsResult(
        descriptions=pulumi.get(__ret__, 'descriptions'),
        id=pulumi.get(__ret__, 'id'),
        ids=pulumi.get(__ret__, 'ids'),
        names=pulumi.get(__ret__, 'names'),
        region=pulumi.get(__ret__, 'region'),
        statuses=pulumi.get(__ret__, 'statuses'),
        transit_subnets=pulumi.get(__ret__, 'transit_subnets'),
        virsubnet_ids=pulumi.get(__ret__, 'virsubnet_ids'),
        virsubnet_project_ids=pulumi.get(__ret__, 'virsubnet_project_ids'),
        vpc_ids=pulumi.get(__ret__, 'vpc_ids'))
def get_private_transit_subnets_output(descriptions: Optional[pulumi.Input[Optional[Sequence[_builtins.str]]]] = None,
                                       ids: Optional[pulumi.Input[Optional[Sequence[_builtins.str]]]] = None,
                                       names: Optional[pulumi.Input[Optional[Sequence[_builtins.str]]]] = None,
                                       region: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                       statuses: Optional[pulumi.Input[Optional[Sequence[_builtins.str]]]] = None,
                                       virsubnet_ids: Optional[pulumi.Input[Optional[Sequence[_builtins.str]]]] = None,
                                       virsubnet_project_ids: Optional[pulumi.Input[Optional[Sequence[_builtins.str]]]] = None,
                                       vpc_ids: Optional[pulumi.Input[Optional[Sequence[_builtins.str]]]] = None,
                                       opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetPrivateTransitSubnetsResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['descriptions'] = descriptions
    __args__['ids'] = ids
    __args__['names'] = names
    __args__['region'] = region
    __args__['statuses'] = statuses
    __args__['virsubnetIds'] = virsubnet_ids
    __args__['virsubnetProjectIds'] = virsubnet_project_ids
    __args__['vpcIds'] = vpc_ids
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('huaweicloud:Nat/getPrivateTransitSubnets:getPrivateTransitSubnets', __args__, opts=opts, typ=GetPrivateTransitSubnetsResult)
    return __ret__.apply(lambda __response__: GetPrivateTransitSubnetsResult(
        descriptions=pulumi.get(__response__, 'descriptions'),
        id=pulumi.get(__response__, 'id'),
        ids=pulumi.get(__response__, 'ids'),
        names=pulumi.get(__response__, 'names'),
        region=pulumi.get(__response__, 'region'),
        statuses=pulumi.get(__response__, 'statuses'),
        transit_subnets=pulumi.get(__response__, 'transit_subnets'),
        virsubnet_ids=pulumi.get(__response__, 'virsubnet_ids'),
        virsubnet_project_ids=pulumi.get(__response__, 'virsubnet_project_ids'),
        vpc_ids=pulumi.get(__response__, 'vpc_ids')))
