# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = [
    'GetPolicySwitchStatusResult',
    'AwaitableGetPolicySwitchStatusResult',
    'get_policy_switch_status',
    'get_policy_switch_status_output',
]

@pulumi.output_type
class GetPolicySwitchStatusResult:
    """
    A collection of values returned by getPolicySwitchStatus.
    """
    def __init__(__self__, enable=None, enterprise_project_id=None, id=None, policy_name=None, region=None):
        if enable and not isinstance(enable, bool):
            raise TypeError("Expected argument 'enable' to be a bool")
        pulumi.set(__self__, "enable", enable)
        if enterprise_project_id and not isinstance(enterprise_project_id, str):
            raise TypeError("Expected argument 'enterprise_project_id' to be a str")
        pulumi.set(__self__, "enterprise_project_id", enterprise_project_id)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if policy_name and not isinstance(policy_name, str):
            raise TypeError("Expected argument 'policy_name' to be a str")
        pulumi.set(__self__, "policy_name", policy_name)
        if region and not isinstance(region, str):
            raise TypeError("Expected argument 'region' to be a str")
        pulumi.set(__self__, "region", region)

    @_builtins.property
    @pulumi.getter
    def enable(self) -> _builtins.bool:
        """
        Whether policy is switch on.
        """
        return pulumi.get(self, "enable")

    @_builtins.property
    @pulumi.getter(name="enterpriseProjectId")
    def enterprise_project_id(self) -> _builtins.str:
        return pulumi.get(self, "enterprise_project_id")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="policyName")
    def policy_name(self) -> _builtins.str:
        return pulumi.get(self, "policy_name")

    @_builtins.property
    @pulumi.getter
    def region(self) -> _builtins.str:
        return pulumi.get(self, "region")


class AwaitableGetPolicySwitchStatusResult(GetPolicySwitchStatusResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetPolicySwitchStatusResult(
            enable=self.enable,
            enterprise_project_id=self.enterprise_project_id,
            id=self.id,
            policy_name=self.policy_name,
            region=self.region)


def get_policy_switch_status(enterprise_project_id: Optional[_builtins.str] = None,
                             policy_name: Optional[_builtins.str] = None,
                             region: Optional[_builtins.str] = None,
                             opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetPolicySwitchStatusResult:
    """
    Use this data source to get the policy switch status of HSS within HuaweiCloud.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_huaweicloud as huaweicloud

    test = huaweicloud.Hss.get_policy_switch_status(enterprise_project_id="all_granted_eps",
        policy_name="sp_feature")
    ```


    :param _builtins.str enterprise_project_id: Specifies the enterprise project ID.
           This parameter only needs to be configured after the Enterprise Project feature is enabled.
           For enterprise users, if omitted, default enterprise project will be used.
           Value **0** means default enterprise project.
           Value **all_granted_eps** means all enterprise projects to which the user has been granted access.
    :param _builtins.str policy_name: Specifies the policy name. Valid value is **sp_feature**.
    :param _builtins.str region: Specifies the region in which to query the resource.
           If omitted, the provider-level region will be used.
    """
    __args__ = dict()
    __args__['enterpriseProjectId'] = enterprise_project_id
    __args__['policyName'] = policy_name
    __args__['region'] = region
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('huaweicloud:Hss/getPolicySwitchStatus:getPolicySwitchStatus', __args__, opts=opts, typ=GetPolicySwitchStatusResult).value

    return AwaitableGetPolicySwitchStatusResult(
        enable=pulumi.get(__ret__, 'enable'),
        enterprise_project_id=pulumi.get(__ret__, 'enterprise_project_id'),
        id=pulumi.get(__ret__, 'id'),
        policy_name=pulumi.get(__ret__, 'policy_name'),
        region=pulumi.get(__ret__, 'region'))
def get_policy_switch_status_output(enterprise_project_id: Optional[pulumi.Input[_builtins.str]] = None,
                                    policy_name: Optional[pulumi.Input[_builtins.str]] = None,
                                    region: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                    opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetPolicySwitchStatusResult]:
    """
    Use this data source to get the policy switch status of HSS within HuaweiCloud.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_huaweicloud as huaweicloud

    test = huaweicloud.Hss.get_policy_switch_status(enterprise_project_id="all_granted_eps",
        policy_name="sp_feature")
    ```


    :param _builtins.str enterprise_project_id: Specifies the enterprise project ID.
           This parameter only needs to be configured after the Enterprise Project feature is enabled.
           For enterprise users, if omitted, default enterprise project will be used.
           Value **0** means default enterprise project.
           Value **all_granted_eps** means all enterprise projects to which the user has been granted access.
    :param _builtins.str policy_name: Specifies the policy name. Valid value is **sp_feature**.
    :param _builtins.str region: Specifies the region in which to query the resource.
           If omitted, the provider-level region will be used.
    """
    __args__ = dict()
    __args__['enterpriseProjectId'] = enterprise_project_id
    __args__['policyName'] = policy_name
    __args__['region'] = region
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('huaweicloud:Hss/getPolicySwitchStatus:getPolicySwitchStatus', __args__, opts=opts, typ=GetPolicySwitchStatusResult)
    return __ret__.apply(lambda __response__: GetPolicySwitchStatusResult(
        enable=pulumi.get(__response__, 'enable'),
        enterprise_project_id=pulumi.get(__response__, 'enterprise_project_id'),
        id=pulumi.get(__response__, 'id'),
        policy_name=pulumi.get(__response__, 'policy_name'),
        region=pulumi.get(__response__, 'region')))
