# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs

__all__ = [
    'GetAssetWebAppServiceStatisticsResult',
    'AwaitableGetAssetWebAppServiceStatisticsResult',
    'get_asset_web_app_service_statistics',
    'get_asset_web_app_service_statistics_output',
]

@pulumi.output_type
class GetAssetWebAppServiceStatisticsResult:
    """
    A collection of values returned by getAssetWebAppServiceStatistics.
    """
    def __init__(__self__, catalogue=None, category=None, data_lists=None, enterprise_project_id=None, id=None, name=None, region=None):
        if catalogue and not isinstance(catalogue, str):
            raise TypeError("Expected argument 'catalogue' to be a str")
        pulumi.set(__self__, "catalogue", catalogue)
        if category and not isinstance(category, str):
            raise TypeError("Expected argument 'category' to be a str")
        pulumi.set(__self__, "category", category)
        if data_lists and not isinstance(data_lists, list):
            raise TypeError("Expected argument 'data_lists' to be a list")
        pulumi.set(__self__, "data_lists", data_lists)
        if enterprise_project_id and not isinstance(enterprise_project_id, str):
            raise TypeError("Expected argument 'enterprise_project_id' to be a str")
        pulumi.set(__self__, "enterprise_project_id", enterprise_project_id)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if region and not isinstance(region, str):
            raise TypeError("Expected argument 'region' to be a str")
        pulumi.set(__self__, "region", region)

    @_builtins.property
    @pulumi.getter
    def catalogue(self) -> _builtins.str:
        return pulumi.get(self, "catalogue")

    @_builtins.property
    @pulumi.getter
    def category(self) -> _builtins.str:
        return pulumi.get(self, "category")

    @_builtins.property
    @pulumi.getter(name="dataLists")
    def data_lists(self) -> Sequence['outputs.GetAssetWebAppServiceStatisticsDataListResult']:
        """
        The list of servers.
        The data_list structure is documented below.
        """
        return pulumi.get(self, "data_lists")

    @_builtins.property
    @pulumi.getter(name="enterpriseProjectId")
    def enterprise_project_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "enterprise_project_id")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[_builtins.str]:
        """
        The web application, web service or database name.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def region(self) -> _builtins.str:
        return pulumi.get(self, "region")


class AwaitableGetAssetWebAppServiceStatisticsResult(GetAssetWebAppServiceStatisticsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetAssetWebAppServiceStatisticsResult(
            catalogue=self.catalogue,
            category=self.category,
            data_lists=self.data_lists,
            enterprise_project_id=self.enterprise_project_id,
            id=self.id,
            name=self.name,
            region=self.region)


def get_asset_web_app_service_statistics(catalogue: Optional[_builtins.str] = None,
                                         category: Optional[_builtins.str] = None,
                                         enterprise_project_id: Optional[_builtins.str] = None,
                                         name: Optional[_builtins.str] = None,
                                         region: Optional[_builtins.str] = None,
                                         opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetAssetWebAppServiceStatisticsResult:
    """
    Use this data source to get the statistics of the web service, web application and database.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_huaweicloud as huaweicloud

    config = pulumi.Config()
    category = config.require_object("category")
    catalogue = config.require_object("catalogue")
    test = huaweicloud.Hss.get_asset_web_app_service_statistics(category=category,
        catalogue=catalogue)
    ```


    :param _builtins.str catalogue: Specifies the asset type.
           The valid values are as follows:
           + **web-app**: Web application.
           + **web-service**: Web service.
           + **database**: Database.
    :param _builtins.str category: Specifies the asset category.
           The valid values are as follows:
           + **host**: Host.
           + **container**: Container.
    :param _builtins.str enterprise_project_id: Specifies the enterprise project ID.
           This parameter is valid only when the enterprise project is enabled.
           The default value is **0**, indicating the default enterprise project.
           If you need to query data for all enterprise projects, the value is **all_granted_eps**.
           If you only have permissions for a specific enterprise project, you need set the enterprise project ID. Otherwise,
           the operation may fail due to insufficient permissions.
    :param _builtins.str name: Specifies the web application, web service or database name.
    :param _builtins.str region: Specifies the region in which to query the resource.
           If omitted, the provider-level region will be used.
    """
    __args__ = dict()
    __args__['catalogue'] = catalogue
    __args__['category'] = category
    __args__['enterpriseProjectId'] = enterprise_project_id
    __args__['name'] = name
    __args__['region'] = region
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('huaweicloud:Hss/getAssetWebAppServiceStatistics:getAssetWebAppServiceStatistics', __args__, opts=opts, typ=GetAssetWebAppServiceStatisticsResult).value

    return AwaitableGetAssetWebAppServiceStatisticsResult(
        catalogue=pulumi.get(__ret__, 'catalogue'),
        category=pulumi.get(__ret__, 'category'),
        data_lists=pulumi.get(__ret__, 'data_lists'),
        enterprise_project_id=pulumi.get(__ret__, 'enterprise_project_id'),
        id=pulumi.get(__ret__, 'id'),
        name=pulumi.get(__ret__, 'name'),
        region=pulumi.get(__ret__, 'region'))
def get_asset_web_app_service_statistics_output(catalogue: Optional[pulumi.Input[_builtins.str]] = None,
                                                category: Optional[pulumi.Input[_builtins.str]] = None,
                                                enterprise_project_id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                                name: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                                region: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                                opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetAssetWebAppServiceStatisticsResult]:
    """
    Use this data source to get the statistics of the web service, web application and database.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_huaweicloud as huaweicloud

    config = pulumi.Config()
    category = config.require_object("category")
    catalogue = config.require_object("catalogue")
    test = huaweicloud.Hss.get_asset_web_app_service_statistics(category=category,
        catalogue=catalogue)
    ```


    :param _builtins.str catalogue: Specifies the asset type.
           The valid values are as follows:
           + **web-app**: Web application.
           + **web-service**: Web service.
           + **database**: Database.
    :param _builtins.str category: Specifies the asset category.
           The valid values are as follows:
           + **host**: Host.
           + **container**: Container.
    :param _builtins.str enterprise_project_id: Specifies the enterprise project ID.
           This parameter is valid only when the enterprise project is enabled.
           The default value is **0**, indicating the default enterprise project.
           If you need to query data for all enterprise projects, the value is **all_granted_eps**.
           If you only have permissions for a specific enterprise project, you need set the enterprise project ID. Otherwise,
           the operation may fail due to insufficient permissions.
    :param _builtins.str name: Specifies the web application, web service or database name.
    :param _builtins.str region: Specifies the region in which to query the resource.
           If omitted, the provider-level region will be used.
    """
    __args__ = dict()
    __args__['catalogue'] = catalogue
    __args__['category'] = category
    __args__['enterpriseProjectId'] = enterprise_project_id
    __args__['name'] = name
    __args__['region'] = region
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('huaweicloud:Hss/getAssetWebAppServiceStatistics:getAssetWebAppServiceStatistics', __args__, opts=opts, typ=GetAssetWebAppServiceStatisticsResult)
    return __ret__.apply(lambda __response__: GetAssetWebAppServiceStatisticsResult(
        catalogue=pulumi.get(__response__, 'catalogue'),
        category=pulumi.get(__response__, 'category'),
        data_lists=pulumi.get(__response__, 'data_lists'),
        enterprise_project_id=pulumi.get(__response__, 'enterprise_project_id'),
        id=pulumi.get(__response__, 'id'),
        name=pulumi.get(__response__, 'name'),
        region=pulumi.get(__response__, 'region')))
