# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs

__all__ = [
    'GetBaselineCheckRuleFailDetailResult',
    'AwaitableGetBaselineCheckRuleFailDetailResult',
    'get_baseline_check_rule_fail_detail',
    'get_baseline_check_rule_fail_detail_output',
]

@pulumi.output_type
class GetBaselineCheckRuleFailDetailResult:
    """
    A collection of values returned by getBaselineCheckRuleFailDetail.
    """
    def __init__(__self__, check_name=None, check_rule_id=None, enterprise_project_id=None, fail_detail_lists=None, host_id=None, id=None, region=None, standard=None):
        if check_name and not isinstance(check_name, str):
            raise TypeError("Expected argument 'check_name' to be a str")
        pulumi.set(__self__, "check_name", check_name)
        if check_rule_id and not isinstance(check_rule_id, str):
            raise TypeError("Expected argument 'check_rule_id' to be a str")
        pulumi.set(__self__, "check_rule_id", check_rule_id)
        if enterprise_project_id and not isinstance(enterprise_project_id, str):
            raise TypeError("Expected argument 'enterprise_project_id' to be a str")
        pulumi.set(__self__, "enterprise_project_id", enterprise_project_id)
        if fail_detail_lists and not isinstance(fail_detail_lists, list):
            raise TypeError("Expected argument 'fail_detail_lists' to be a list")
        pulumi.set(__self__, "fail_detail_lists", fail_detail_lists)
        if host_id and not isinstance(host_id, str):
            raise TypeError("Expected argument 'host_id' to be a str")
        pulumi.set(__self__, "host_id", host_id)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if region and not isinstance(region, str):
            raise TypeError("Expected argument 'region' to be a str")
        pulumi.set(__self__, "region", region)
        if standard and not isinstance(standard, str):
            raise TypeError("Expected argument 'standard' to be a str")
        pulumi.set(__self__, "standard", standard)

    @_builtins.property
    @pulumi.getter(name="checkName")
    def check_name(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "check_name")

    @_builtins.property
    @pulumi.getter(name="checkRuleId")
    def check_rule_id(self) -> _builtins.str:
        return pulumi.get(self, "check_rule_id")

    @_builtins.property
    @pulumi.getter(name="enterpriseProjectId")
    def enterprise_project_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "enterprise_project_id")

    @_builtins.property
    @pulumi.getter(name="failDetailLists")
    def fail_detail_lists(self) -> Sequence['outputs.GetBaselineCheckRuleFailDetailFailDetailListResult']:
        """
        The list of check rule fix fail detail.
        """
        return pulumi.get(self, "fail_detail_lists")

    @_builtins.property
    @pulumi.getter(name="hostId")
    def host_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "host_id")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def region(self) -> _builtins.str:
        return pulumi.get(self, "region")

    @_builtins.property
    @pulumi.getter
    def standard(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "standard")


class AwaitableGetBaselineCheckRuleFailDetailResult(GetBaselineCheckRuleFailDetailResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetBaselineCheckRuleFailDetailResult(
            check_name=self.check_name,
            check_rule_id=self.check_rule_id,
            enterprise_project_id=self.enterprise_project_id,
            fail_detail_lists=self.fail_detail_lists,
            host_id=self.host_id,
            id=self.id,
            region=self.region,
            standard=self.standard)


def get_baseline_check_rule_fail_detail(check_name: Optional[_builtins.str] = None,
                                        check_rule_id: Optional[_builtins.str] = None,
                                        enterprise_project_id: Optional[_builtins.str] = None,
                                        host_id: Optional[_builtins.str] = None,
                                        region: Optional[_builtins.str] = None,
                                        standard: Optional[_builtins.str] = None,
                                        opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetBaselineCheckRuleFailDetailResult:
    """
    Use this data source to get the list of HSS baseline check rule fail detail within HuaweiCloud.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_huaweicloud as huaweicloud

    config = pulumi.Config()
    check_rule_id = config.require_object("checkRuleId")
    test = huaweicloud.Hss.get_baseline_check_rule_fail_detail(check_rule_id=check_rule_id)
    ```


    :param _builtins.str check_name: Specifies the configuration check (baseline) name.
           For example: **SSH**, **CentOS 7**, **Windows**.
    :param _builtins.str check_rule_id: Specifies the check item ID.
           The value of this parameter can query from dataSource `hss_get_baseline_risk_config_check_rules`.
    :param _builtins.str enterprise_project_id: Specifies the enterprise project ID.  
           This parameter is valid only when the enterprise project is enabled.
           The default value is **0**, indicating the default enterprise project.
           If you need to query data for all enterprise projects, the value is **all_granted_eps**.
           If you only have permissions for a specific enterprise project, you need set the enterprise project ID. Otherwise,
           the operation may fail due to insufficient permissions.
    :param _builtins.str host_id: Specifies the server ID.
    :param _builtins.str region: Specifies the region in which to query the data source.
           If omitted, the provider-level region will be used.
    :param _builtins.str standard: Specifies the standard type. Valid values are:
           + **cn_standard**: DJCP MLPS compliance standard.
           + **hw_standard**: Cloud security practice standard.
           + **cis_standard**: Common security standard.
    """
    __args__ = dict()
    __args__['checkName'] = check_name
    __args__['checkRuleId'] = check_rule_id
    __args__['enterpriseProjectId'] = enterprise_project_id
    __args__['hostId'] = host_id
    __args__['region'] = region
    __args__['standard'] = standard
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('huaweicloud:Hss/getBaselineCheckRuleFailDetail:getBaselineCheckRuleFailDetail', __args__, opts=opts, typ=GetBaselineCheckRuleFailDetailResult).value

    return AwaitableGetBaselineCheckRuleFailDetailResult(
        check_name=pulumi.get(__ret__, 'check_name'),
        check_rule_id=pulumi.get(__ret__, 'check_rule_id'),
        enterprise_project_id=pulumi.get(__ret__, 'enterprise_project_id'),
        fail_detail_lists=pulumi.get(__ret__, 'fail_detail_lists'),
        host_id=pulumi.get(__ret__, 'host_id'),
        id=pulumi.get(__ret__, 'id'),
        region=pulumi.get(__ret__, 'region'),
        standard=pulumi.get(__ret__, 'standard'))
def get_baseline_check_rule_fail_detail_output(check_name: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                               check_rule_id: Optional[pulumi.Input[_builtins.str]] = None,
                                               enterprise_project_id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                               host_id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                               region: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                               standard: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                               opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetBaselineCheckRuleFailDetailResult]:
    """
    Use this data source to get the list of HSS baseline check rule fail detail within HuaweiCloud.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_huaweicloud as huaweicloud

    config = pulumi.Config()
    check_rule_id = config.require_object("checkRuleId")
    test = huaweicloud.Hss.get_baseline_check_rule_fail_detail(check_rule_id=check_rule_id)
    ```


    :param _builtins.str check_name: Specifies the configuration check (baseline) name.
           For example: **SSH**, **CentOS 7**, **Windows**.
    :param _builtins.str check_rule_id: Specifies the check item ID.
           The value of this parameter can query from dataSource `hss_get_baseline_risk_config_check_rules`.
    :param _builtins.str enterprise_project_id: Specifies the enterprise project ID.  
           This parameter is valid only when the enterprise project is enabled.
           The default value is **0**, indicating the default enterprise project.
           If you need to query data for all enterprise projects, the value is **all_granted_eps**.
           If you only have permissions for a specific enterprise project, you need set the enterprise project ID. Otherwise,
           the operation may fail due to insufficient permissions.
    :param _builtins.str host_id: Specifies the server ID.
    :param _builtins.str region: Specifies the region in which to query the data source.
           If omitted, the provider-level region will be used.
    :param _builtins.str standard: Specifies the standard type. Valid values are:
           + **cn_standard**: DJCP MLPS compliance standard.
           + **hw_standard**: Cloud security practice standard.
           + **cis_standard**: Common security standard.
    """
    __args__ = dict()
    __args__['checkName'] = check_name
    __args__['checkRuleId'] = check_rule_id
    __args__['enterpriseProjectId'] = enterprise_project_id
    __args__['hostId'] = host_id
    __args__['region'] = region
    __args__['standard'] = standard
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('huaweicloud:Hss/getBaselineCheckRuleFailDetail:getBaselineCheckRuleFailDetail', __args__, opts=opts, typ=GetBaselineCheckRuleFailDetailResult)
    return __ret__.apply(lambda __response__: GetBaselineCheckRuleFailDetailResult(
        check_name=pulumi.get(__response__, 'check_name'),
        check_rule_id=pulumi.get(__response__, 'check_rule_id'),
        enterprise_project_id=pulumi.get(__response__, 'enterprise_project_id'),
        fail_detail_lists=pulumi.get(__response__, 'fail_detail_lists'),
        host_id=pulumi.get(__response__, 'host_id'),
        id=pulumi.get(__response__, 'id'),
        region=pulumi.get(__response__, 'region'),
        standard=pulumi.get(__response__, 'standard')))
