# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = ['SettingTwoFactorLoginConfigArgs', 'SettingTwoFactorLoginConfig']

@pulumi.input_type
class SettingTwoFactorLoginConfigArgs:
    def __init__(__self__, *,
                 auth_type: pulumi.Input[_builtins.str],
                 enabled: pulumi.Input[_builtins.bool],
                 host_id_lists: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]],
                 enable_force_new: Optional[pulumi.Input[_builtins.str]] = None,
                 enterprise_project_id: Optional[pulumi.Input[_builtins.str]] = None,
                 region: Optional[pulumi.Input[_builtins.str]] = None,
                 topic_display_name: Optional[pulumi.Input[_builtins.str]] = None,
                 topic_urn: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a SettingTwoFactorLoginConfig resource.

        :param pulumi.Input[_builtins.str] auth_type: Specifies the authentication type.
               The valid values are as follows:
               + **sms**: Indicates SMS and email verification.
               + **code**: Indicates captcha code verification.
        :param pulumi.Input[_builtins.bool] enabled: Specifies whether the two-factor authentication enabled.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] host_id_lists: Specifies the host IDs.
        :param pulumi.Input[_builtins.str] enterprise_project_id: Specifies the enterprise project ID.
               This parameter is valid only when the enterprise project is enabled.
               The default value is **0**, indicating the default enterprise project.
               If it is necessary to operate the hosts under all enterprise projects, the value is **all_granted_eps**.
               If you only have permissions for a specific enterprise project, you need set the enterprise project ID. Otherwise,
               the operation may fail due to insufficient permissions.
        :param pulumi.Input[_builtins.str] region: Specifies the region in which to create the resource.
               If omitted, the provider-level region will be used.
               Changing this parameter will create a new resource.
        :param pulumi.Input[_builtins.str] topic_display_name: Specifies the SMN topic display name.
        :param pulumi.Input[_builtins.str] topic_urn: Specifies the SMN topic urn.
               
               > The field `topic_display_name` and `topic_urn` are valid only when `auth_type` is set to **sms**.
        """
        pulumi.set(__self__, "auth_type", auth_type)
        pulumi.set(__self__, "enabled", enabled)
        pulumi.set(__self__, "host_id_lists", host_id_lists)
        if enable_force_new is not None:
            pulumi.set(__self__, "enable_force_new", enable_force_new)
        if enterprise_project_id is not None:
            pulumi.set(__self__, "enterprise_project_id", enterprise_project_id)
        if region is not None:
            pulumi.set(__self__, "region", region)
        if topic_display_name is not None:
            pulumi.set(__self__, "topic_display_name", topic_display_name)
        if topic_urn is not None:
            pulumi.set(__self__, "topic_urn", topic_urn)

    @_builtins.property
    @pulumi.getter(name="authType")
    def auth_type(self) -> pulumi.Input[_builtins.str]:
        """
        Specifies the authentication type.
        The valid values are as follows:
        + **sms**: Indicates SMS and email verification.
        + **code**: Indicates captcha code verification.
        """
        return pulumi.get(self, "auth_type")

    @auth_type.setter
    def auth_type(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "auth_type", value)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Input[_builtins.bool]:
        """
        Specifies whether the two-factor authentication enabled.
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: pulumi.Input[_builtins.bool]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter(name="hostIdLists")
    def host_id_lists(self) -> pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]:
        """
        Specifies the host IDs.
        """
        return pulumi.get(self, "host_id_lists")

    @host_id_lists.setter
    def host_id_lists(self, value: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]):
        pulumi.set(self, "host_id_lists", value)

    @_builtins.property
    @pulumi.getter(name="enableForceNew")
    def enable_force_new(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "enable_force_new")

    @enable_force_new.setter
    def enable_force_new(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "enable_force_new", value)

    @_builtins.property
    @pulumi.getter(name="enterpriseProjectId")
    def enterprise_project_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Specifies the enterprise project ID.
        This parameter is valid only when the enterprise project is enabled.
        The default value is **0**, indicating the default enterprise project.
        If it is necessary to operate the hosts under all enterprise projects, the value is **all_granted_eps**.
        If you only have permissions for a specific enterprise project, you need set the enterprise project ID. Otherwise,
        the operation may fail due to insufficient permissions.
        """
        return pulumi.get(self, "enterprise_project_id")

    @enterprise_project_id.setter
    def enterprise_project_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "enterprise_project_id", value)

    @_builtins.property
    @pulumi.getter
    def region(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Specifies the region in which to create the resource.
        If omitted, the provider-level region will be used.
        Changing this parameter will create a new resource.
        """
        return pulumi.get(self, "region")

    @region.setter
    def region(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "region", value)

    @_builtins.property
    @pulumi.getter(name="topicDisplayName")
    def topic_display_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Specifies the SMN topic display name.
        """
        return pulumi.get(self, "topic_display_name")

    @topic_display_name.setter
    def topic_display_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "topic_display_name", value)

    @_builtins.property
    @pulumi.getter(name="topicUrn")
    def topic_urn(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Specifies the SMN topic urn.

        > The field `topic_display_name` and `topic_urn` are valid only when `auth_type` is set to **sms**.
        """
        return pulumi.get(self, "topic_urn")

    @topic_urn.setter
    def topic_urn(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "topic_urn", value)


@pulumi.input_type
class _SettingTwoFactorLoginConfigState:
    def __init__(__self__, *,
                 auth_type: Optional[pulumi.Input[_builtins.str]] = None,
                 enable_force_new: Optional[pulumi.Input[_builtins.str]] = None,
                 enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 enterprise_project_id: Optional[pulumi.Input[_builtins.str]] = None,
                 host_id_lists: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 region: Optional[pulumi.Input[_builtins.str]] = None,
                 topic_display_name: Optional[pulumi.Input[_builtins.str]] = None,
                 topic_urn: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering SettingTwoFactorLoginConfig resources.

        :param pulumi.Input[_builtins.str] auth_type: Specifies the authentication type.
               The valid values are as follows:
               + **sms**: Indicates SMS and email verification.
               + **code**: Indicates captcha code verification.
        :param pulumi.Input[_builtins.bool] enabled: Specifies whether the two-factor authentication enabled.
        :param pulumi.Input[_builtins.str] enterprise_project_id: Specifies the enterprise project ID.
               This parameter is valid only when the enterprise project is enabled.
               The default value is **0**, indicating the default enterprise project.
               If it is necessary to operate the hosts under all enterprise projects, the value is **all_granted_eps**.
               If you only have permissions for a specific enterprise project, you need set the enterprise project ID. Otherwise,
               the operation may fail due to insufficient permissions.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] host_id_lists: Specifies the host IDs.
        :param pulumi.Input[_builtins.str] region: Specifies the region in which to create the resource.
               If omitted, the provider-level region will be used.
               Changing this parameter will create a new resource.
        :param pulumi.Input[_builtins.str] topic_display_name: Specifies the SMN topic display name.
        :param pulumi.Input[_builtins.str] topic_urn: Specifies the SMN topic urn.
               
               > The field `topic_display_name` and `topic_urn` are valid only when `auth_type` is set to **sms**.
        """
        if auth_type is not None:
            pulumi.set(__self__, "auth_type", auth_type)
        if enable_force_new is not None:
            pulumi.set(__self__, "enable_force_new", enable_force_new)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if enterprise_project_id is not None:
            pulumi.set(__self__, "enterprise_project_id", enterprise_project_id)
        if host_id_lists is not None:
            pulumi.set(__self__, "host_id_lists", host_id_lists)
        if region is not None:
            pulumi.set(__self__, "region", region)
        if topic_display_name is not None:
            pulumi.set(__self__, "topic_display_name", topic_display_name)
        if topic_urn is not None:
            pulumi.set(__self__, "topic_urn", topic_urn)

    @_builtins.property
    @pulumi.getter(name="authType")
    def auth_type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Specifies the authentication type.
        The valid values are as follows:
        + **sms**: Indicates SMS and email verification.
        + **code**: Indicates captcha code verification.
        """
        return pulumi.get(self, "auth_type")

    @auth_type.setter
    def auth_type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "auth_type", value)

    @_builtins.property
    @pulumi.getter(name="enableForceNew")
    def enable_force_new(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "enable_force_new")

    @enable_force_new.setter
    def enable_force_new(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "enable_force_new", value)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Specifies whether the two-factor authentication enabled.
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter(name="enterpriseProjectId")
    def enterprise_project_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Specifies the enterprise project ID.
        This parameter is valid only when the enterprise project is enabled.
        The default value is **0**, indicating the default enterprise project.
        If it is necessary to operate the hosts under all enterprise projects, the value is **all_granted_eps**.
        If you only have permissions for a specific enterprise project, you need set the enterprise project ID. Otherwise,
        the operation may fail due to insufficient permissions.
        """
        return pulumi.get(self, "enterprise_project_id")

    @enterprise_project_id.setter
    def enterprise_project_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "enterprise_project_id", value)

    @_builtins.property
    @pulumi.getter(name="hostIdLists")
    def host_id_lists(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Specifies the host IDs.
        """
        return pulumi.get(self, "host_id_lists")

    @host_id_lists.setter
    def host_id_lists(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "host_id_lists", value)

    @_builtins.property
    @pulumi.getter
    def region(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Specifies the region in which to create the resource.
        If omitted, the provider-level region will be used.
        Changing this parameter will create a new resource.
        """
        return pulumi.get(self, "region")

    @region.setter
    def region(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "region", value)

    @_builtins.property
    @pulumi.getter(name="topicDisplayName")
    def topic_display_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Specifies the SMN topic display name.
        """
        return pulumi.get(self, "topic_display_name")

    @topic_display_name.setter
    def topic_display_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "topic_display_name", value)

    @_builtins.property
    @pulumi.getter(name="topicUrn")
    def topic_urn(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Specifies the SMN topic urn.

        > The field `topic_display_name` and `topic_urn` are valid only when `auth_type` is set to **sms**.
        """
        return pulumi.get(self, "topic_urn")

    @topic_urn.setter
    def topic_urn(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "topic_urn", value)


@pulumi.type_token("huaweicloud:Hss/settingTwoFactorLoginConfig:SettingTwoFactorLoginConfig")
class SettingTwoFactorLoginConfig(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 auth_type: Optional[pulumi.Input[_builtins.str]] = None,
                 enable_force_new: Optional[pulumi.Input[_builtins.str]] = None,
                 enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 enterprise_project_id: Optional[pulumi.Input[_builtins.str]] = None,
                 host_id_lists: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 region: Optional[pulumi.Input[_builtins.str]] = None,
                 topic_display_name: Optional[pulumi.Input[_builtins.str]] = None,
                 topic_urn: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Manages a resource to set two-factor login configuration within HuaweiCloud.

        > This resource is a one-time action resource. Deleting this resource will not clear the corresponding request record,
          but will only remove the resource information from the tf state file.


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] auth_type: Specifies the authentication type.
               The valid values are as follows:
               + **sms**: Indicates SMS and email verification.
               + **code**: Indicates captcha code verification.
        :param pulumi.Input[_builtins.bool] enabled: Specifies whether the two-factor authentication enabled.
        :param pulumi.Input[_builtins.str] enterprise_project_id: Specifies the enterprise project ID.
               This parameter is valid only when the enterprise project is enabled.
               The default value is **0**, indicating the default enterprise project.
               If it is necessary to operate the hosts under all enterprise projects, the value is **all_granted_eps**.
               If you only have permissions for a specific enterprise project, you need set the enterprise project ID. Otherwise,
               the operation may fail due to insufficient permissions.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] host_id_lists: Specifies the host IDs.
        :param pulumi.Input[_builtins.str] region: Specifies the region in which to create the resource.
               If omitted, the provider-level region will be used.
               Changing this parameter will create a new resource.
        :param pulumi.Input[_builtins.str] topic_display_name: Specifies the SMN topic display name.
        :param pulumi.Input[_builtins.str] topic_urn: Specifies the SMN topic urn.
               
               > The field `topic_display_name` and `topic_urn` are valid only when `auth_type` is set to **sms**.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: SettingTwoFactorLoginConfigArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Manages a resource to set two-factor login configuration within HuaweiCloud.

        > This resource is a one-time action resource. Deleting this resource will not clear the corresponding request record,
          but will only remove the resource information from the tf state file.


        :param str resource_name: The name of the resource.
        :param SettingTwoFactorLoginConfigArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(SettingTwoFactorLoginConfigArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 auth_type: Optional[pulumi.Input[_builtins.str]] = None,
                 enable_force_new: Optional[pulumi.Input[_builtins.str]] = None,
                 enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 enterprise_project_id: Optional[pulumi.Input[_builtins.str]] = None,
                 host_id_lists: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 region: Optional[pulumi.Input[_builtins.str]] = None,
                 topic_display_name: Optional[pulumi.Input[_builtins.str]] = None,
                 topic_urn: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = SettingTwoFactorLoginConfigArgs.__new__(SettingTwoFactorLoginConfigArgs)

            if auth_type is None and not opts.urn:
                raise TypeError("Missing required property 'auth_type'")
            __props__.__dict__["auth_type"] = auth_type
            __props__.__dict__["enable_force_new"] = enable_force_new
            if enabled is None and not opts.urn:
                raise TypeError("Missing required property 'enabled'")
            __props__.__dict__["enabled"] = enabled
            __props__.__dict__["enterprise_project_id"] = enterprise_project_id
            if host_id_lists is None and not opts.urn:
                raise TypeError("Missing required property 'host_id_lists'")
            __props__.__dict__["host_id_lists"] = host_id_lists
            __props__.__dict__["region"] = region
            __props__.__dict__["topic_display_name"] = topic_display_name
            __props__.__dict__["topic_urn"] = topic_urn
        super(SettingTwoFactorLoginConfig, __self__).__init__(
            'huaweicloud:Hss/settingTwoFactorLoginConfig:SettingTwoFactorLoginConfig',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            auth_type: Optional[pulumi.Input[_builtins.str]] = None,
            enable_force_new: Optional[pulumi.Input[_builtins.str]] = None,
            enabled: Optional[pulumi.Input[_builtins.bool]] = None,
            enterprise_project_id: Optional[pulumi.Input[_builtins.str]] = None,
            host_id_lists: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            region: Optional[pulumi.Input[_builtins.str]] = None,
            topic_display_name: Optional[pulumi.Input[_builtins.str]] = None,
            topic_urn: Optional[pulumi.Input[_builtins.str]] = None) -> 'SettingTwoFactorLoginConfig':
        """
        Get an existing SettingTwoFactorLoginConfig resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] auth_type: Specifies the authentication type.
               The valid values are as follows:
               + **sms**: Indicates SMS and email verification.
               + **code**: Indicates captcha code verification.
        :param pulumi.Input[_builtins.bool] enabled: Specifies whether the two-factor authentication enabled.
        :param pulumi.Input[_builtins.str] enterprise_project_id: Specifies the enterprise project ID.
               This parameter is valid only when the enterprise project is enabled.
               The default value is **0**, indicating the default enterprise project.
               If it is necessary to operate the hosts under all enterprise projects, the value is **all_granted_eps**.
               If you only have permissions for a specific enterprise project, you need set the enterprise project ID. Otherwise,
               the operation may fail due to insufficient permissions.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] host_id_lists: Specifies the host IDs.
        :param pulumi.Input[_builtins.str] region: Specifies the region in which to create the resource.
               If omitted, the provider-level region will be used.
               Changing this parameter will create a new resource.
        :param pulumi.Input[_builtins.str] topic_display_name: Specifies the SMN topic display name.
        :param pulumi.Input[_builtins.str] topic_urn: Specifies the SMN topic urn.
               
               > The field `topic_display_name` and `topic_urn` are valid only when `auth_type` is set to **sms**.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _SettingTwoFactorLoginConfigState.__new__(_SettingTwoFactorLoginConfigState)

        __props__.__dict__["auth_type"] = auth_type
        __props__.__dict__["enable_force_new"] = enable_force_new
        __props__.__dict__["enabled"] = enabled
        __props__.__dict__["enterprise_project_id"] = enterprise_project_id
        __props__.__dict__["host_id_lists"] = host_id_lists
        __props__.__dict__["region"] = region
        __props__.__dict__["topic_display_name"] = topic_display_name
        __props__.__dict__["topic_urn"] = topic_urn
        return SettingTwoFactorLoginConfig(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="authType")
    def auth_type(self) -> pulumi.Output[_builtins.str]:
        """
        Specifies the authentication type.
        The valid values are as follows:
        + **sms**: Indicates SMS and email verification.
        + **code**: Indicates captcha code verification.
        """
        return pulumi.get(self, "auth_type")

    @_builtins.property
    @pulumi.getter(name="enableForceNew")
    def enable_force_new(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "enable_force_new")

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Output[_builtins.bool]:
        """
        Specifies whether the two-factor authentication enabled.
        """
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter(name="enterpriseProjectId")
    def enterprise_project_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Specifies the enterprise project ID.
        This parameter is valid only when the enterprise project is enabled.
        The default value is **0**, indicating the default enterprise project.
        If it is necessary to operate the hosts under all enterprise projects, the value is **all_granted_eps**.
        If you only have permissions for a specific enterprise project, you need set the enterprise project ID. Otherwise,
        the operation may fail due to insufficient permissions.
        """
        return pulumi.get(self, "enterprise_project_id")

    @_builtins.property
    @pulumi.getter(name="hostIdLists")
    def host_id_lists(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        Specifies the host IDs.
        """
        return pulumi.get(self, "host_id_lists")

    @_builtins.property
    @pulumi.getter
    def region(self) -> pulumi.Output[_builtins.str]:
        """
        Specifies the region in which to create the resource.
        If omitted, the provider-level region will be used.
        Changing this parameter will create a new resource.
        """
        return pulumi.get(self, "region")

    @_builtins.property
    @pulumi.getter(name="topicDisplayName")
    def topic_display_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Specifies the SMN topic display name.
        """
        return pulumi.get(self, "topic_display_name")

    @_builtins.property
    @pulumi.getter(name="topicUrn")
    def topic_urn(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Specifies the SMN topic urn.

        > The field `topic_display_name` and `topic_urn` are valid only when `auth_type` is set to **sms**.
        """
        return pulumi.get(self, "topic_urn")

