# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = ['KeyReplicateArgs', 'KeyReplicate']

@pulumi.input_type
class KeyReplicateArgs:
    def __init__(__self__, *,
                 key_alias: pulumi.Input[_builtins.str],
                 key_id: pulumi.Input[_builtins.str],
                 replica_project_id: pulumi.Input[_builtins.str],
                 replica_region: pulumi.Input[_builtins.str],
                 enable_force_new: Optional[pulumi.Input[_builtins.str]] = None,
                 enterprise_project_id: Optional[pulumi.Input[_builtins.str]] = None,
                 key_description: Optional[pulumi.Input[_builtins.str]] = None,
                 region: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None):
        """
        The set of arguments for constructing a KeyReplicate resource.

        :param pulumi.Input[_builtins.str] key_alias: Specifies the alias of the replicated key.
               The alias must be unique in the target region and project.
        :param pulumi.Input[_builtins.str] key_id: Specifies the ID of the key to be replicated.
               The valid length is `36` bytes, meeting regular match **^[0-9a-z]{8}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{12}$**.
               For example: **0d0466b0-e727-4d9c-b35d-f84bb474a37f**.
        :param pulumi.Input[_builtins.str] replica_project_id: Specifies the target project ID to which the key is replicated.
        :param pulumi.Input[_builtins.str] replica_region: Specifies the target region to which the key is replicated.
               The value should be a valid region name, such as **cn-north-4**.
               The value of this field cannot be the same as the region in the source key.
        :param pulumi.Input[_builtins.str] enterprise_project_id: Specifies the enterprise project ID of the replicated key.
               If omitted, the default enterprise project is used.
        :param pulumi.Input[_builtins.str] key_description: Specifies the description of the replicated key.
        :param pulumi.Input[_builtins.str] region: Specifies the region in which to create the resource.
               If omitted, the provider-level region will be used.
               Changing this creates a new resource.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] tags: Specifies the key/value pairs to associate with the replicated key.
        """
        pulumi.set(__self__, "key_alias", key_alias)
        pulumi.set(__self__, "key_id", key_id)
        pulumi.set(__self__, "replica_project_id", replica_project_id)
        pulumi.set(__self__, "replica_region", replica_region)
        if enable_force_new is not None:
            pulumi.set(__self__, "enable_force_new", enable_force_new)
        if enterprise_project_id is not None:
            pulumi.set(__self__, "enterprise_project_id", enterprise_project_id)
        if key_description is not None:
            pulumi.set(__self__, "key_description", key_description)
        if region is not None:
            pulumi.set(__self__, "region", region)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)

    @_builtins.property
    @pulumi.getter(name="keyAlias")
    def key_alias(self) -> pulumi.Input[_builtins.str]:
        """
        Specifies the alias of the replicated key.
        The alias must be unique in the target region and project.
        """
        return pulumi.get(self, "key_alias")

    @key_alias.setter
    def key_alias(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "key_alias", value)

    @_builtins.property
    @pulumi.getter(name="keyId")
    def key_id(self) -> pulumi.Input[_builtins.str]:
        """
        Specifies the ID of the key to be replicated.
        The valid length is `36` bytes, meeting regular match **^[0-9a-z]{8}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{12}$**.
        For example: **0d0466b0-e727-4d9c-b35d-f84bb474a37f**.
        """
        return pulumi.get(self, "key_id")

    @key_id.setter
    def key_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "key_id", value)

    @_builtins.property
    @pulumi.getter(name="replicaProjectId")
    def replica_project_id(self) -> pulumi.Input[_builtins.str]:
        """
        Specifies the target project ID to which the key is replicated.
        """
        return pulumi.get(self, "replica_project_id")

    @replica_project_id.setter
    def replica_project_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "replica_project_id", value)

    @_builtins.property
    @pulumi.getter(name="replicaRegion")
    def replica_region(self) -> pulumi.Input[_builtins.str]:
        """
        Specifies the target region to which the key is replicated.
        The value should be a valid region name, such as **cn-north-4**.
        The value of this field cannot be the same as the region in the source key.
        """
        return pulumi.get(self, "replica_region")

    @replica_region.setter
    def replica_region(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "replica_region", value)

    @_builtins.property
    @pulumi.getter(name="enableForceNew")
    def enable_force_new(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "enable_force_new")

    @enable_force_new.setter
    def enable_force_new(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "enable_force_new", value)

    @_builtins.property
    @pulumi.getter(name="enterpriseProjectId")
    def enterprise_project_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Specifies the enterprise project ID of the replicated key.
        If omitted, the default enterprise project is used.
        """
        return pulumi.get(self, "enterprise_project_id")

    @enterprise_project_id.setter
    def enterprise_project_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "enterprise_project_id", value)

    @_builtins.property
    @pulumi.getter(name="keyDescription")
    def key_description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Specifies the description of the replicated key.
        """
        return pulumi.get(self, "key_description")

    @key_description.setter
    def key_description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "key_description", value)

    @_builtins.property
    @pulumi.getter
    def region(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Specifies the region in which to create the resource.
        If omitted, the provider-level region will be used.
        Changing this creates a new resource.
        """
        return pulumi.get(self, "region")

    @region.setter
    def region(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "region", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Specifies the key/value pairs to associate with the replicated key.
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)


@pulumi.input_type
class _KeyReplicateState:
    def __init__(__self__, *,
                 enable_force_new: Optional[pulumi.Input[_builtins.str]] = None,
                 enterprise_project_id: Optional[pulumi.Input[_builtins.str]] = None,
                 key_alias: Optional[pulumi.Input[_builtins.str]] = None,
                 key_description: Optional[pulumi.Input[_builtins.str]] = None,
                 key_id: Optional[pulumi.Input[_builtins.str]] = None,
                 region: Optional[pulumi.Input[_builtins.str]] = None,
                 replica_project_id: Optional[pulumi.Input[_builtins.str]] = None,
                 replica_region: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None):
        """
        Input properties used for looking up and filtering KeyReplicate resources.

        :param pulumi.Input[_builtins.str] enterprise_project_id: Specifies the enterprise project ID of the replicated key.
               If omitted, the default enterprise project is used.
        :param pulumi.Input[_builtins.str] key_alias: Specifies the alias of the replicated key.
               The alias must be unique in the target region and project.
        :param pulumi.Input[_builtins.str] key_description: Specifies the description of the replicated key.
        :param pulumi.Input[_builtins.str] key_id: Specifies the ID of the key to be replicated.
               The valid length is `36` bytes, meeting regular match **^[0-9a-z]{8}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{12}$**.
               For example: **0d0466b0-e727-4d9c-b35d-f84bb474a37f**.
        :param pulumi.Input[_builtins.str] region: Specifies the region in which to create the resource.
               If omitted, the provider-level region will be used.
               Changing this creates a new resource.
        :param pulumi.Input[_builtins.str] replica_project_id: Specifies the target project ID to which the key is replicated.
        :param pulumi.Input[_builtins.str] replica_region: Specifies the target region to which the key is replicated.
               The value should be a valid region name, such as **cn-north-4**.
               The value of this field cannot be the same as the region in the source key.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] tags: Specifies the key/value pairs to associate with the replicated key.
        """
        if enable_force_new is not None:
            pulumi.set(__self__, "enable_force_new", enable_force_new)
        if enterprise_project_id is not None:
            pulumi.set(__self__, "enterprise_project_id", enterprise_project_id)
        if key_alias is not None:
            pulumi.set(__self__, "key_alias", key_alias)
        if key_description is not None:
            pulumi.set(__self__, "key_description", key_description)
        if key_id is not None:
            pulumi.set(__self__, "key_id", key_id)
        if region is not None:
            pulumi.set(__self__, "region", region)
        if replica_project_id is not None:
            pulumi.set(__self__, "replica_project_id", replica_project_id)
        if replica_region is not None:
            pulumi.set(__self__, "replica_region", replica_region)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)

    @_builtins.property
    @pulumi.getter(name="enableForceNew")
    def enable_force_new(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "enable_force_new")

    @enable_force_new.setter
    def enable_force_new(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "enable_force_new", value)

    @_builtins.property
    @pulumi.getter(name="enterpriseProjectId")
    def enterprise_project_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Specifies the enterprise project ID of the replicated key.
        If omitted, the default enterprise project is used.
        """
        return pulumi.get(self, "enterprise_project_id")

    @enterprise_project_id.setter
    def enterprise_project_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "enterprise_project_id", value)

    @_builtins.property
    @pulumi.getter(name="keyAlias")
    def key_alias(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Specifies the alias of the replicated key.
        The alias must be unique in the target region and project.
        """
        return pulumi.get(self, "key_alias")

    @key_alias.setter
    def key_alias(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "key_alias", value)

    @_builtins.property
    @pulumi.getter(name="keyDescription")
    def key_description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Specifies the description of the replicated key.
        """
        return pulumi.get(self, "key_description")

    @key_description.setter
    def key_description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "key_description", value)

    @_builtins.property
    @pulumi.getter(name="keyId")
    def key_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Specifies the ID of the key to be replicated.
        The valid length is `36` bytes, meeting regular match **^[0-9a-z]{8}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{12}$**.
        For example: **0d0466b0-e727-4d9c-b35d-f84bb474a37f**.
        """
        return pulumi.get(self, "key_id")

    @key_id.setter
    def key_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "key_id", value)

    @_builtins.property
    @pulumi.getter
    def region(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Specifies the region in which to create the resource.
        If omitted, the provider-level region will be used.
        Changing this creates a new resource.
        """
        return pulumi.get(self, "region")

    @region.setter
    def region(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "region", value)

    @_builtins.property
    @pulumi.getter(name="replicaProjectId")
    def replica_project_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Specifies the target project ID to which the key is replicated.
        """
        return pulumi.get(self, "replica_project_id")

    @replica_project_id.setter
    def replica_project_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "replica_project_id", value)

    @_builtins.property
    @pulumi.getter(name="replicaRegion")
    def replica_region(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Specifies the target region to which the key is replicated.
        The value should be a valid region name, such as **cn-north-4**.
        The value of this field cannot be the same as the region in the source key.
        """
        return pulumi.get(self, "replica_region")

    @replica_region.setter
    def replica_region(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "replica_region", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Specifies the key/value pairs to associate with the replicated key.
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)


@pulumi.type_token("huaweicloud:Dew/keyReplicate:KeyReplicate")
class KeyReplicate(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 enable_force_new: Optional[pulumi.Input[_builtins.str]] = None,
                 enterprise_project_id: Optional[pulumi.Input[_builtins.str]] = None,
                 key_alias: Optional[pulumi.Input[_builtins.str]] = None,
                 key_description: Optional[pulumi.Input[_builtins.str]] = None,
                 key_id: Optional[pulumi.Input[_builtins.str]] = None,
                 region: Optional[pulumi.Input[_builtins.str]] = None,
                 replica_project_id: Optional[pulumi.Input[_builtins.str]] = None,
                 replica_region: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        """
        Manages a KMS key replication resource within HuaweiCloud.

        > The current resource is a one-time resource, and destroying this resource will not delete the replicated key,
          but will only remove the resource information from the tfstate file.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_huaweicloud as huaweicloud

        config = pulumi.Config()
        key_id = config.require_object("keyId")
        replica_region = config.require_object("replicaRegion")
        key_alias = config.require_object("keyAlias")
        replica_project_id = config.require_object("replicaProjectId")
        test = huaweicloud.dew.KeyReplicate("test",
            key_id=key_id,
            replica_region=replica_region,
            key_alias=key_alias,
            replica_project_id=replica_project_id,
            key_description="Replicated key for cross-region usage",
            tags={
                "environment": "production",
                "owner": "security",
            })
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] enterprise_project_id: Specifies the enterprise project ID of the replicated key.
               If omitted, the default enterprise project is used.
        :param pulumi.Input[_builtins.str] key_alias: Specifies the alias of the replicated key.
               The alias must be unique in the target region and project.
        :param pulumi.Input[_builtins.str] key_description: Specifies the description of the replicated key.
        :param pulumi.Input[_builtins.str] key_id: Specifies the ID of the key to be replicated.
               The valid length is `36` bytes, meeting regular match **^[0-9a-z]{8}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{12}$**.
               For example: **0d0466b0-e727-4d9c-b35d-f84bb474a37f**.
        :param pulumi.Input[_builtins.str] region: Specifies the region in which to create the resource.
               If omitted, the provider-level region will be used.
               Changing this creates a new resource.
        :param pulumi.Input[_builtins.str] replica_project_id: Specifies the target project ID to which the key is replicated.
        :param pulumi.Input[_builtins.str] replica_region: Specifies the target region to which the key is replicated.
               The value should be a valid region name, such as **cn-north-4**.
               The value of this field cannot be the same as the region in the source key.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] tags: Specifies the key/value pairs to associate with the replicated key.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: KeyReplicateArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Manages a KMS key replication resource within HuaweiCloud.

        > The current resource is a one-time resource, and destroying this resource will not delete the replicated key,
          but will only remove the resource information from the tfstate file.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_huaweicloud as huaweicloud

        config = pulumi.Config()
        key_id = config.require_object("keyId")
        replica_region = config.require_object("replicaRegion")
        key_alias = config.require_object("keyAlias")
        replica_project_id = config.require_object("replicaProjectId")
        test = huaweicloud.dew.KeyReplicate("test",
            key_id=key_id,
            replica_region=replica_region,
            key_alias=key_alias,
            replica_project_id=replica_project_id,
            key_description="Replicated key for cross-region usage",
            tags={
                "environment": "production",
                "owner": "security",
            })
        ```


        :param str resource_name: The name of the resource.
        :param KeyReplicateArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(KeyReplicateArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 enable_force_new: Optional[pulumi.Input[_builtins.str]] = None,
                 enterprise_project_id: Optional[pulumi.Input[_builtins.str]] = None,
                 key_alias: Optional[pulumi.Input[_builtins.str]] = None,
                 key_description: Optional[pulumi.Input[_builtins.str]] = None,
                 key_id: Optional[pulumi.Input[_builtins.str]] = None,
                 region: Optional[pulumi.Input[_builtins.str]] = None,
                 replica_project_id: Optional[pulumi.Input[_builtins.str]] = None,
                 replica_region: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = KeyReplicateArgs.__new__(KeyReplicateArgs)

            __props__.__dict__["enable_force_new"] = enable_force_new
            __props__.__dict__["enterprise_project_id"] = enterprise_project_id
            if key_alias is None and not opts.urn:
                raise TypeError("Missing required property 'key_alias'")
            __props__.__dict__["key_alias"] = key_alias
            __props__.__dict__["key_description"] = key_description
            if key_id is None and not opts.urn:
                raise TypeError("Missing required property 'key_id'")
            __props__.__dict__["key_id"] = key_id
            __props__.__dict__["region"] = region
            if replica_project_id is None and not opts.urn:
                raise TypeError("Missing required property 'replica_project_id'")
            __props__.__dict__["replica_project_id"] = replica_project_id
            if replica_region is None and not opts.urn:
                raise TypeError("Missing required property 'replica_region'")
            __props__.__dict__["replica_region"] = replica_region
            __props__.__dict__["tags"] = tags
        super(KeyReplicate, __self__).__init__(
            'huaweicloud:Dew/keyReplicate:KeyReplicate',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            enable_force_new: Optional[pulumi.Input[_builtins.str]] = None,
            enterprise_project_id: Optional[pulumi.Input[_builtins.str]] = None,
            key_alias: Optional[pulumi.Input[_builtins.str]] = None,
            key_description: Optional[pulumi.Input[_builtins.str]] = None,
            key_id: Optional[pulumi.Input[_builtins.str]] = None,
            region: Optional[pulumi.Input[_builtins.str]] = None,
            replica_project_id: Optional[pulumi.Input[_builtins.str]] = None,
            replica_region: Optional[pulumi.Input[_builtins.str]] = None,
            tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None) -> 'KeyReplicate':
        """
        Get an existing KeyReplicate resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] enterprise_project_id: Specifies the enterprise project ID of the replicated key.
               If omitted, the default enterprise project is used.
        :param pulumi.Input[_builtins.str] key_alias: Specifies the alias of the replicated key.
               The alias must be unique in the target region and project.
        :param pulumi.Input[_builtins.str] key_description: Specifies the description of the replicated key.
        :param pulumi.Input[_builtins.str] key_id: Specifies the ID of the key to be replicated.
               The valid length is `36` bytes, meeting regular match **^[0-9a-z]{8}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{12}$**.
               For example: **0d0466b0-e727-4d9c-b35d-f84bb474a37f**.
        :param pulumi.Input[_builtins.str] region: Specifies the region in which to create the resource.
               If omitted, the provider-level region will be used.
               Changing this creates a new resource.
        :param pulumi.Input[_builtins.str] replica_project_id: Specifies the target project ID to which the key is replicated.
        :param pulumi.Input[_builtins.str] replica_region: Specifies the target region to which the key is replicated.
               The value should be a valid region name, such as **cn-north-4**.
               The value of this field cannot be the same as the region in the source key.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] tags: Specifies the key/value pairs to associate with the replicated key.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _KeyReplicateState.__new__(_KeyReplicateState)

        __props__.__dict__["enable_force_new"] = enable_force_new
        __props__.__dict__["enterprise_project_id"] = enterprise_project_id
        __props__.__dict__["key_alias"] = key_alias
        __props__.__dict__["key_description"] = key_description
        __props__.__dict__["key_id"] = key_id
        __props__.__dict__["region"] = region
        __props__.__dict__["replica_project_id"] = replica_project_id
        __props__.__dict__["replica_region"] = replica_region
        __props__.__dict__["tags"] = tags
        return KeyReplicate(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="enableForceNew")
    def enable_force_new(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "enable_force_new")

    @_builtins.property
    @pulumi.getter(name="enterpriseProjectId")
    def enterprise_project_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Specifies the enterprise project ID of the replicated key.
        If omitted, the default enterprise project is used.
        """
        return pulumi.get(self, "enterprise_project_id")

    @_builtins.property
    @pulumi.getter(name="keyAlias")
    def key_alias(self) -> pulumi.Output[_builtins.str]:
        """
        Specifies the alias of the replicated key.
        The alias must be unique in the target region and project.
        """
        return pulumi.get(self, "key_alias")

    @_builtins.property
    @pulumi.getter(name="keyDescription")
    def key_description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Specifies the description of the replicated key.
        """
        return pulumi.get(self, "key_description")

    @_builtins.property
    @pulumi.getter(name="keyId")
    def key_id(self) -> pulumi.Output[_builtins.str]:
        """
        Specifies the ID of the key to be replicated.
        The valid length is `36` bytes, meeting regular match **^[0-9a-z]{8}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{12}$**.
        For example: **0d0466b0-e727-4d9c-b35d-f84bb474a37f**.
        """
        return pulumi.get(self, "key_id")

    @_builtins.property
    @pulumi.getter
    def region(self) -> pulumi.Output[_builtins.str]:
        """
        Specifies the region in which to create the resource.
        If omitted, the provider-level region will be used.
        Changing this creates a new resource.
        """
        return pulumi.get(self, "region")

    @_builtins.property
    @pulumi.getter(name="replicaProjectId")
    def replica_project_id(self) -> pulumi.Output[_builtins.str]:
        """
        Specifies the target project ID to which the key is replicated.
        """
        return pulumi.get(self, "replica_project_id")

    @_builtins.property
    @pulumi.getter(name="replicaRegion")
    def replica_region(self) -> pulumi.Output[_builtins.str]:
        """
        Specifies the target region to which the key is replicated.
        The value should be a valid region name, such as **cn-north-4**.
        The value of this field cannot be the same as the region in the source key.
        """
        return pulumi.get(self, "replica_region")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Output[Mapping[str, _builtins.str]]:
        """
        Specifies the key/value pairs to associate with the replicated key.
        """
        return pulumi.get(self, "tags")

