# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs

__all__ = [
    'GetAllPolicyCcRulesResult',
    'AwaitableGetAllPolicyCcRulesResult',
    'get_all_policy_cc_rules',
    'get_all_policy_cc_rules_output',
]

@pulumi.output_type
class GetAllPolicyCcRulesResult:
    """
    A collection of values returned by getAllPolicyCcRules.
    """
    def __init__(__self__, enterprise_project_id=None, id=None, items=None, policyids=None, region=None):
        if enterprise_project_id and not isinstance(enterprise_project_id, str):
            raise TypeError("Expected argument 'enterprise_project_id' to be a str")
        pulumi.set(__self__, "enterprise_project_id", enterprise_project_id)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if items and not isinstance(items, list):
            raise TypeError("Expected argument 'items' to be a list")
        pulumi.set(__self__, "items", items)
        if policyids and not isinstance(policyids, str):
            raise TypeError("Expected argument 'policyids' to be a str")
        pulumi.set(__self__, "policyids", policyids)
        if region and not isinstance(region, str):
            raise TypeError("Expected argument 'region' to be a str")
        pulumi.set(__self__, "region", region)

    @_builtins.property
    @pulumi.getter(name="enterpriseProjectId")
    def enterprise_project_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "enterprise_project_id")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def items(self) -> Sequence['outputs.GetAllPolicyCcRulesItemResult']:
        return pulumi.get(self, "items")

    @_builtins.property
    @pulumi.getter
    def policyids(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "policyids")

    @_builtins.property
    @pulumi.getter
    def region(self) -> _builtins.str:
        return pulumi.get(self, "region")


class AwaitableGetAllPolicyCcRulesResult(GetAllPolicyCcRulesResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetAllPolicyCcRulesResult(
            enterprise_project_id=self.enterprise_project_id,
            id=self.id,
            items=self.items,
            policyids=self.policyids,
            region=self.region)


def get_all_policy_cc_rules(enterprise_project_id: Optional[_builtins.str] = None,
                            policyids: Optional[_builtins.str] = None,
                            region: Optional[_builtins.str] = None,
                            opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetAllPolicyCcRulesResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['enterpriseProjectId'] = enterprise_project_id
    __args__['policyids'] = policyids
    __args__['region'] = region
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('huaweicloud:Waf/getAllPolicyCcRules:getAllPolicyCcRules', __args__, opts=opts, typ=GetAllPolicyCcRulesResult).value

    return AwaitableGetAllPolicyCcRulesResult(
        enterprise_project_id=pulumi.get(__ret__, 'enterprise_project_id'),
        id=pulumi.get(__ret__, 'id'),
        items=pulumi.get(__ret__, 'items'),
        policyids=pulumi.get(__ret__, 'policyids'),
        region=pulumi.get(__ret__, 'region'))
def get_all_policy_cc_rules_output(enterprise_project_id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                   policyids: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                   region: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                   opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetAllPolicyCcRulesResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['enterpriseProjectId'] = enterprise_project_id
    __args__['policyids'] = policyids
    __args__['region'] = region
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('huaweicloud:Waf/getAllPolicyCcRules:getAllPolicyCcRules', __args__, opts=opts, typ=GetAllPolicyCcRulesResult)
    return __ret__.apply(lambda __response__: GetAllPolicyCcRulesResult(
        enterprise_project_id=pulumi.get(__response__, 'enterprise_project_id'),
        id=pulumi.get(__response__, 'id'),
        items=pulumi.get(__response__, 'items'),
        policyids=pulumi.get(__response__, 'policyids'),
        region=pulumi.get(__response__, 'region')))
