# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs

__all__ = [
    'GetAppHdaLatestVersionsResult',
    'AwaitableGetAppHdaLatestVersionsResult',
    'get_app_hda_latest_versions',
    'get_app_hda_latest_versions_output',
]

@pulumi.output_type
class GetAppHdaLatestVersionsResult:
    """
    A collection of values returned by getAppHdaLatestVersions.
    """
    def __init__(__self__, hda_latest_versions=None, id=None, region=None):
        if hda_latest_versions and not isinstance(hda_latest_versions, list):
            raise TypeError("Expected argument 'hda_latest_versions' to be a list")
        pulumi.set(__self__, "hda_latest_versions", hda_latest_versions)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if region and not isinstance(region, str):
            raise TypeError("Expected argument 'region' to be a str")
        pulumi.set(__self__, "region", region)

    @_builtins.property
    @pulumi.getter(name="hdaLatestVersions")
    def hda_latest_versions(self) -> Sequence['outputs.GetAppHdaLatestVersionsHdaLatestVersionResult']:
        """
        The list of HDA latest versions that matched filter parameters.  
        The hda_latest_versions structure is documented below.
        """
        return pulumi.get(self, "hda_latest_versions")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def region(self) -> _builtins.str:
        return pulumi.get(self, "region")


class AwaitableGetAppHdaLatestVersionsResult(GetAppHdaLatestVersionsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetAppHdaLatestVersionsResult(
            hda_latest_versions=self.hda_latest_versions,
            id=self.id,
            region=self.region)


def get_app_hda_latest_versions(region: Optional[_builtins.str] = None,
                                opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetAppHdaLatestVersionsResult:
    """
    Use this data source to get HDA latest versions under a specified region of the Workspace APP within HuaweiCloud.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_huaweicloud as huaweicloud

    test = huaweicloud.Workspace.get_app_hda_latest_versions()
    ```


    :param _builtins.str region: Specifies the region where the HDA latest versions are located.  
           If omitted, the provider-level region will be used.
    """
    __args__ = dict()
    __args__['region'] = region
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('huaweicloud:Workspace/getAppHdaLatestVersions:getAppHdaLatestVersions', __args__, opts=opts, typ=GetAppHdaLatestVersionsResult).value

    return AwaitableGetAppHdaLatestVersionsResult(
        hda_latest_versions=pulumi.get(__ret__, 'hda_latest_versions'),
        id=pulumi.get(__ret__, 'id'),
        region=pulumi.get(__ret__, 'region'))
def get_app_hda_latest_versions_output(region: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                       opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetAppHdaLatestVersionsResult]:
    """
    Use this data source to get HDA latest versions under a specified region of the Workspace APP within HuaweiCloud.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_huaweicloud as huaweicloud

    test = huaweicloud.Workspace.get_app_hda_latest_versions()
    ```


    :param _builtins.str region: Specifies the region where the HDA latest versions are located.  
           If omitted, the provider-level region will be used.
    """
    __args__ = dict()
    __args__['region'] = region
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('huaweicloud:Workspace/getAppHdaLatestVersions:getAppHdaLatestVersions', __args__, opts=opts, typ=GetAppHdaLatestVersionsResult)
    return __ret__.apply(lambda __response__: GetAppHdaLatestVersionsResult(
        hda_latest_versions=pulumi.get(__response__, 'hda_latest_versions'),
        id=pulumi.get(__response__, 'id'),
        region=pulumi.get(__response__, 'region')))
