# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs

__all__ = [
    'GetRetrieveScriptsResult',
    'AwaitableGetRetrieveScriptsResult',
    'get_retrieve_scripts',
    'get_retrieve_scripts_output',
]

@pulumi.output_type
class GetRetrieveScriptsResult:
    """
    A collection of values returned by getRetrieveScripts.
    """
    def __init__(__self__, id=None, records=None, region=None, script_name=None, sort_dir=None, sort_key=None, table_id=None, workspace_id=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if records and not isinstance(records, list):
            raise TypeError("Expected argument 'records' to be a list")
        pulumi.set(__self__, "records", records)
        if region and not isinstance(region, str):
            raise TypeError("Expected argument 'region' to be a str")
        pulumi.set(__self__, "region", region)
        if script_name and not isinstance(script_name, str):
            raise TypeError("Expected argument 'script_name' to be a str")
        pulumi.set(__self__, "script_name", script_name)
        if sort_dir and not isinstance(sort_dir, str):
            raise TypeError("Expected argument 'sort_dir' to be a str")
        pulumi.set(__self__, "sort_dir", sort_dir)
        if sort_key and not isinstance(sort_key, str):
            raise TypeError("Expected argument 'sort_key' to be a str")
        pulumi.set(__self__, "sort_key", sort_key)
        if table_id and not isinstance(table_id, str):
            raise TypeError("Expected argument 'table_id' to be a str")
        pulumi.set(__self__, "table_id", table_id)
        if workspace_id and not isinstance(workspace_id, str):
            raise TypeError("Expected argument 'workspace_id' to be a str")
        pulumi.set(__self__, "workspace_id", workspace_id)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def records(self) -> Sequence['outputs.GetRetrieveScriptsRecordResult']:
        """
        The retrieve scripts list.
        """
        return pulumi.get(self, "records")

    @_builtins.property
    @pulumi.getter
    def region(self) -> _builtins.str:
        return pulumi.get(self, "region")

    @_builtins.property
    @pulumi.getter(name="scriptName")
    def script_name(self) -> Optional[_builtins.str]:
        """
        The script name.
        """
        return pulumi.get(self, "script_name")

    @_builtins.property
    @pulumi.getter(name="sortDir")
    def sort_dir(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "sort_dir")

    @_builtins.property
    @pulumi.getter(name="sortKey")
    def sort_key(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "sort_key")

    @_builtins.property
    @pulumi.getter(name="tableId")
    def table_id(self) -> Optional[_builtins.str]:
        """
        The table ID.
        """
        return pulumi.get(self, "table_id")

    @_builtins.property
    @pulumi.getter(name="workspaceId")
    def workspace_id(self) -> _builtins.str:
        """
        The workspace ID.
        """
        return pulumi.get(self, "workspace_id")


class AwaitableGetRetrieveScriptsResult(GetRetrieveScriptsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetRetrieveScriptsResult(
            id=self.id,
            records=self.records,
            region=self.region,
            script_name=self.script_name,
            sort_dir=self.sort_dir,
            sort_key=self.sort_key,
            table_id=self.table_id,
            workspace_id=self.workspace_id)


def get_retrieve_scripts(region: Optional[_builtins.str] = None,
                         script_name: Optional[_builtins.str] = None,
                         sort_dir: Optional[_builtins.str] = None,
                         sort_key: Optional[_builtins.str] = None,
                         table_id: Optional[_builtins.str] = None,
                         workspace_id: Optional[_builtins.str] = None,
                         opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetRetrieveScriptsResult:
    """
    Use this data source to get the list of SecMaster retrieve scripts within HuaweiCloud.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_huaweicloud as huaweicloud

    config = pulumi.Config()
    workspace_id = config.require_object("workspaceId")
    test = huaweicloud.Secmaster.get_retrieve_scripts(workspace_id=workspace_id)
    ```


    :param _builtins.str region: Specifies the region in which to query the resource.
           If omitted, the provider-level region will be used.
    :param _builtins.str script_name: Specifies the script name.
    :param _builtins.str sort_dir: Specifies the sorting order. Supported values are **ASC** and **DESC**.
    :param _builtins.str sort_key: Specifies the attribute fields for sorting.
    :param _builtins.str table_id: Specifies the table ID.
    :param _builtins.str workspace_id: Specifies the workspace ID.
    """
    __args__ = dict()
    __args__['region'] = region
    __args__['scriptName'] = script_name
    __args__['sortDir'] = sort_dir
    __args__['sortKey'] = sort_key
    __args__['tableId'] = table_id
    __args__['workspaceId'] = workspace_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('huaweicloud:Secmaster/getRetrieveScripts:getRetrieveScripts', __args__, opts=opts, typ=GetRetrieveScriptsResult).value

    return AwaitableGetRetrieveScriptsResult(
        id=pulumi.get(__ret__, 'id'),
        records=pulumi.get(__ret__, 'records'),
        region=pulumi.get(__ret__, 'region'),
        script_name=pulumi.get(__ret__, 'script_name'),
        sort_dir=pulumi.get(__ret__, 'sort_dir'),
        sort_key=pulumi.get(__ret__, 'sort_key'),
        table_id=pulumi.get(__ret__, 'table_id'),
        workspace_id=pulumi.get(__ret__, 'workspace_id'))
def get_retrieve_scripts_output(region: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                script_name: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                sort_dir: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                sort_key: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                table_id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                workspace_id: Optional[pulumi.Input[_builtins.str]] = None,
                                opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetRetrieveScriptsResult]:
    """
    Use this data source to get the list of SecMaster retrieve scripts within HuaweiCloud.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_huaweicloud as huaweicloud

    config = pulumi.Config()
    workspace_id = config.require_object("workspaceId")
    test = huaweicloud.Secmaster.get_retrieve_scripts(workspace_id=workspace_id)
    ```


    :param _builtins.str region: Specifies the region in which to query the resource.
           If omitted, the provider-level region will be used.
    :param _builtins.str script_name: Specifies the script name.
    :param _builtins.str sort_dir: Specifies the sorting order. Supported values are **ASC** and **DESC**.
    :param _builtins.str sort_key: Specifies the attribute fields for sorting.
    :param _builtins.str table_id: Specifies the table ID.
    :param _builtins.str workspace_id: Specifies the workspace ID.
    """
    __args__ = dict()
    __args__['region'] = region
    __args__['scriptName'] = script_name
    __args__['sortDir'] = sort_dir
    __args__['sortKey'] = sort_key
    __args__['tableId'] = table_id
    __args__['workspaceId'] = workspace_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('huaweicloud:Secmaster/getRetrieveScripts:getRetrieveScripts', __args__, opts=opts, typ=GetRetrieveScriptsResult)
    return __ret__.apply(lambda __response__: GetRetrieveScriptsResult(
        id=pulumi.get(__response__, 'id'),
        records=pulumi.get(__response__, 'records'),
        region=pulumi.get(__response__, 'region'),
        script_name=pulumi.get(__response__, 'script_name'),
        sort_dir=pulumi.get(__response__, 'sort_dir'),
        sort_key=pulumi.get(__response__, 'sort_key'),
        table_id=pulumi.get(__response__, 'table_id'),
        workspace_id=pulumi.get(__response__, 'workspace_id')))
